<?php

define('EVENT_STATUS_UNDEFINED', '');
define('EVENT_STATUS_NEW', 1);
define('EVENT_STATUS_PENDING', 2);
define('EVENT_STATUS_ACCEPTED', 3);
define('EVENT_STATUS_DECLINED', 4);

function events_menu(){
  $items = array(
    'create_event_if_valid' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'create_event_if_valid',
      'access callback' => 'user_is_logged_in'
    ),
    
    'check_event_fields' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'check_event_fields',
      'access callback' => 'user_is_logged_in'
    ),
    
    'check_event_form_values' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'check_event_form_values',
      'access callback' => 'user_is_logged_in'
    ),
    
    'event_post_comment' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'event_post_comment',
      'access callback' => 'user_is_logged_in'
    ),
    
    'add_event_for_user' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'add_event_for_user',
      'access callback' => 'user_is_logged_in'
    ),
    
    'remove_event_for_user' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'remove_event_for_user',
      'access callback' => 'user_is_logged_in'
    ),
    
    'public' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'events_public_page',
      'access callback' => 'user_is_logged_in'
    ),
    'private' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'events_private_page',
      'access callback' => 'user_is_logged_in'
    ),
    
    'show_events/%' => array(
      'type' => MENU_CALLBACK,
      'page callback' => 'show_events',
      'page arguments' => array(1),
      'access callback' => 'user_is_logged_in'
    ),
    
  );
  return $items;
  
}

function events_block($op = 'list', $delta = 0, $edit = array()) {
    if ($op == 'list') {
        $blocks[0] = array(
            'title' => t('Event Photos Right'),
            'info' => t('Event Photos Right'),
            'weight' => 0,
        );
        
        $blocks[1] = array(
            'title' => t('Events Activity Stream'),
            'info' => t('Events Activity Stream'),
            'weight' => 0,
        );
        
        $blocks[2] = array(
            'title' => t('Latest Events Photos'),
            'info' => t('Latest Events Photos'),
        );
        
        return $blocks;
    } else if ($op == 'view') {
        switch ($delta) {
          case 0:
            $block = array(
              'content' => events_get_events_photos(),
            );
            break; 
            
          case 1:
            $block = array(
              'content' => events_get_user_activity_stream(),
            );
            break;
          
           case 2:
            $block = array(
              'content' => events_get_latest_events_photos(),
            );
            break;     
            
        }
        return $block;
    }
}



function events_theme() {
    return array(
      'create_event_form' => array(
        'template' => 'create-event',
        'path' => drupal_get_path('theme',variable_get('theme_default',''))
      ),
      'event_photos_list' => array(
        'template' => 'event-photos-list',
        'arguments' => array('content' => NULL, 'photos_count' => NULL),
        'path' => drupal_get_path('theme',variable_get('theme_default',''))
      ),
      'events_invited_list' => array(
        'template' => 'events-invited-list',
        'arguments' => array('events' => NULL, 'public' => NULL),
        'path' => drupal_get_path('theme',variable_get('theme_default',''))
      ),
      'events_accepted_list' => array(
        'template' => 'events-accepted-list',
        'arguments' => array('events' => NULL, 'public' => NULL),
        'path' => drupal_get_path('theme',variable_get('theme_default',''))
      ),
      'event_post_box' => array(
        'template' =>'event-post-box',
        'path' => drupal_get_path('theme',variable_get('theme_default','')),
      ),
      
      'latest_events_photos' => array(
        'template' =>'latest-events-photos',
        'path' => drupal_get_path('theme',variable_get('theme_default','')),
        'arguments' => array('photos' => NULL, 'photos_count' => NULL)
      )
      
      
    );
}

function events_form_alter(&$form, &$form_state, $form_id) {
   
}


function events_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $user;
  switch ($op) {
    case 'view':
      if($node->type == 'event'){
        $view = views_get_view('nodecomments');
        $view->set_display('nodecomment_comments_1');
        $args = array($node->nid);
        $view->set_arguments($args);
        $node->comments_form = theme('event_post_box');
        $node->comments_view = $view->render('nodecomment_comments_1');
        $node->current_user_status = events_get_event_status_for_user($node->nid, $user->uid);
        
      }
      if($node->type == 'comment'){
        global $user;
        if($node->uid != $user->uid){
          $node->user_info = user_load($node->uid);
        }
        else{
          $node->user_info = $user;
        }
      }
      break;  
  }
}

function check_event_fields($values, &$errors){
  $is_valid = true;
  if(!isset($values['title']) || empty($values['title'])){
    $errors['title'] = t('Enter event title'); 
    $is_valid = false;
  }
  
  if(!isset($values['details']) || empty($values['details'])){
    $errors['details'] = t('Enter event details'); 
    $is_valid = false;
  }
  
  if(!isset($values['location']) || empty($values['location'])){
    $errors['location'] = t('Enter event location'); 
    $is_valid = false;
  }
  
  if(!isset($values['date']) || empty($values['date'])){
    $errors['date'] = t('Enter event date'); 
    $is_valid = false;
  }
  
  if(isset($values['date']) && !empty($values['date']) && strtotime($values['date']) == -1){
    $errors['date'] = t('Enter valid date'); 
    $is_valid = false;
  }
  if(isset($values['date']) && !empty($values['date'])){
    if(!preg_match('/^([1-9]|0[1-9]|[12][0-9]|3[01])\/([1-9]|0[1-9]|1[012])\/(2)\d\d\d$/',$values['date'])){
      $errors['date'] = t('Date format: d/m/Y'); 
      $is_valid = false;
    }
  }
  
  if(!isset($values['time']) || empty($values['time'])){
    $errors['time'] = t('Enter event time'); 
    $is_valid = false;
  }
  
  if(isset($values['time']) && !empty($values['time'])){
    if(!preg_match('/^(([0-9])|([0-1][0-9])|([2][0-3])):(([0-9])|([0-5][0-9]))(\s*-\s*(([0-9])|([0-1][0-9])|([2][0-3])):(([0-9])|([0-5][0-9])))?$/',$values['time'])){
      $errors['time'] = t('Enter valid time'); 
      $is_valid = false;
    }
  }
  
  
  if(isset($values['email']) && !empty($values['email']) && !valid_email_address($values['email'])){
    $errors['email'] = t('Enter valid e-mail address'); 
    $is_valid = false;
  }
  
  return $is_valid;
}

function check_event_form_values(){
  if(isset($_POST)){
    $errors = $return = array();
    $is_valid = check_event_fields($_POST, $errors);  
    if(!$is_valid){
      $return = array('isValid' => false, 'errors'=>$errors);
    }
    else 
    $return = array('isValid' => true);  
  }
  else $return = array('success' => false);
  
  echo json_encode($return);
  exit;
}

function create_event_if_valid(){
  
  if(isset($_POST)){
    $errors = $return = array();
    $is_valid = check_event_fields($_POST, $errors);
    if(!$is_valid){
      
    } else{
      
      global $user;   
      $event = new stdClass();
      $event->type = 'event';
      $event->uid = $user->uid;
      $event->status = 1;
      $event->title = trim($_POST['title']);
      $event->field_event_details[0]['value']= trim($_POST['details']);
      $event->field_location[0]['value']= trim($_POST['location']);
      $date_arr = explode('/',trim($_POST['date']));
      $time = $_POST['time']; 
      if(strpos($time,'-') !== false)
        $time = trim(substr($_POST['time'],0,strpos($_POST['time'],'-')));
      $time = explode(':',$time);  
      $event->field_date[0]['value']= $event->field_date[0]['value2']= date('c', mktime($time[0],$time[1],0,$date_arr[1],$date_arr[0],$date_arr[2]));
      $event->field_event_email[0]['value']= $_POST['email'];
      $event->field_event_contact_phone[0]['value']= $_POST['phone'];
      if(in_array('professional', $user->roles)){
         $event->field_event_gratuity[0]['value']= $_POST['gratuity'];  
        
      }
      $event->field_event_type[0]['value']= (in_array('individual', $user->roles) ? 'private' : 'public');
      if ($file = file_save_upload('photo')) {
        $event->field_content_images[0] = (array)$file;  
      }
      
      node_save($event);
      
      // Create specal comment 'Event created'
      global $user;   
      $comment = new stdClass();
      $comment->type = 'comment';
      $comment->title = '<EventCreated>';
      $comment->uid = $user->uid;
      $comment->name = $user->name;
      $comment->status = 1;
      $comment->body = trim($_POST['comment_body']);
      node_save($comment);

      if($comment->nid > 0){
        $comment->comment_target_nid = $event->nid; 
         nodecomment_save($comment);
      }      
      
      $query = '';
      if (!empty($_POST['invite'])) {
        $invite_str = implode(',', $_POST['invite']);
        $query = 'invite=' . $invite_str . '&event_id=' . $event->nid;
      }
      
      if($event->nid > 0)
        drupal_goto('node/'.$event->nid, $query);
      else drupal_goto('<front>');  
      //die();
    }
  }
  return '';
}

function events_get_events_photos(){
  
  $res = db_query("SELECT field_comment_photo_fid, f.*
                      FROM content_field_comment_photo ph
                      INNER JOIN node comment_nid on comment_nid.nid = ph.nid
                      INNER JOIN node_comments nc on nc.cid = comment_nid.nid
                      INNER JOIN files f on f.fid = field_comment_photo_fid
                      WHERE nc.nid = %d AND field_comment_photo_fid IS NOT NULL
                      ORDER BY comment_nid.created DESC
                      LIMIT 7
                      ",arg(1));
  while ($r = db_fetch_array($res)) {
    $photos[] = $r;
  }
  
  $count_res = db_query("SELECT count(field_comment_photo_fid) as photos_count
                      FROM content_field_comment_photo ph
                      INNER JOIN node comment_nid on comment_nid.nid = ph.nid
                      INNER JOIN node_comments nc on nc.cid = comment_nid.nid
                      WHERE nc.nid = %d AND field_comment_photo_fid IS NOT NULL
                      ",arg(1));                      
  
  $count = db_fetch_array($count_res);
  $count = $count['photos_count'];
                     
  $photos_html = '';
  foreach($photos as $_photo){
    $photos_html .= '<div class="item"><a href="'.imagecache_create_url('comment_image_big',$_photo['filepath']).'">'.theme_imagecache('comment_image_right_thumbnail',$_photo['filepath']).'</a></div>';
  }
  //$view = views_get_view('event_photos');
  //$view->set_display('block_1');
  //$view->set_arguments(array(arg(1)));
  return theme('event_photos_list',$photos_html, $count);//$view->render('block_1');
}

function event_post_comment(){
  if(isset($_POST) && isset($_POST['comment_target_nid']) && ($_POST['comment_target_nid'] > 0) && (isset($_POST['comment_body']) || isset($_FILES['files']['photo']))){
    
    global $user;   
    $comment = new stdClass();
    $comment->type = 'comment';
    $comment->title = 'Comment "'.substr($_POST['comment_body'],0, 20).'..." from '.$user->name.' for node '.$_POST['comment_target_nid'];
    $comment->uid = $user->uid;
    $comment->name = $user->name;
    $comment->status = 1;
    $comment->body = trim($_POST['comment_body']);

    if(!empty($_FILES['files'])){
      $_index = 0;
      foreach($_FILES['files']['name'] as $_name => $_ph){
        if ($file = file_save_upload($_name)) {
          $comment->field_comment_photo[$_index++] = (array)$file;      
        }
      }
    }
    
    /*echo '<pre>';
    print_r($_FILES);
    print_r($comment);
    die();*/
    
    node_save($comment);
    if($comment->nid > 0){
      $comment->comment_target_nid = (int)$_POST['comment_target_nid']; 
       nodecomment_save($comment);
    }
    drupal_goto('node/'.$_POST['comment_target_nid']);
  }
  
}


function events_get_user_events_with_status($user_id = null, $status = EVENT_STATUS_ACCEPTED){
  $events = array();
  if(empty($user)){
    global $user;
    $user_id = $user->uid;
  }  
  $res = db_query('SELECT * from {events_users} where user_id = %d AND status = %d',$user->uid, $status);
  while ($r = db_fetch_array($res)) {
    $events[] = $r['event_id'];
  }
  return $events;
}

function events_get_events_created_by_user($user_id = null, $load_full_node = false){
  $events = array();
  if(empty($user_id)){
    global $user;
    $user_id = $user->uid;
  }  
  $res = db_query('SELECT * from {node} where uid = %d AND type=\'event\' AND status = 1',$user_id);
  while ($r = db_fetch_array($res)) {
    if($load_full_node)
      $events[$r['nid']] = $r['nid'];
    else
      $events[] = $r['nid'];
  }
  return $events;
}

function events_get_event_status_for_user($event_id = null, $user_id = null){
  $status = '';       
  if(!empty($event_id) && !empty($user_id)){
    $res = db_query('SELECT status from {events_users} where user_id = %d AND event_id = %d',$user_id, $event_id); 
    $status = db_fetch_array($res);
    $status = $status['status'];
  }
  return $status;
}

function events_event_is_available_to_add($node){
  global $user;
  if(!isset($node->uid)){
    if(isset($node->users_uid)){
      $node->uid = $node->users_uid;
    }
    else{
      $_node = node_load($node->nid);
      $node->uid = $_node->uid;
    }
  }
    
  return (user_is_logged_in() && in_array('individual', $user->roles) && ($user->uid != $node->uid) && events_get_event_status_for_user($node->nid, $user->uid) != EVENT_STATUS_ACCEPTED);
}

function add_event_for_user(){
  $res = false;
  if(isset($_POST) && isset($_POST['event_id'])){
    global $user;
    $event_id = (int)$_POST['event_id'];
    $event_node = node_load($event_id);
    if(events_event_is_available_to_add($event_node)){
      $data = array('event_id' => $event_id, 'sender_id' => $user->uid, 'user_id' => $user->uid, 'status' => EVENT_STATUS_ACCEPTED);
      if(events_get_event_status_for_user($event_id, $user->uid) != EVENT_STATUS_UNDEFINED)
        $res = drupal_write_record('events_users', $data, array('event_id', 'user_id'));  
      else
        $res = drupal_write_record('events_users', $data);    
    }
  }
  $output = array('success' => $res);
 
    
  echo json_encode($output);
  exit;
}

function remove_event_for_user(){
  $res = false;
  if(isset($_POST) && isset($_POST['event_id'])){
    global $user;
    $event_id = (int)$_POST['event_id'];
    //$event_node = node_load($event_id);
    $data = array('event_id' => $event_id, 'sender_id' => $user->uid, 'user_id' => $user->uid, 'status' => EVENT_STATUS_DECLINED);
    $res = drupal_write_record('events_users', $data, array('event_id', 'user_id'));  
  }
  $output = array('success' => $res, 'ee' => $data);
    
  echo json_encode($output);
  exit;
}

function events_preprocess_page(&$variables) {
    $variables['menu_stats']['public_pending'] = events_get_count(EVENT_STATUS_NEW, true);
    $variables['menu_stats']['private_pending'] = events_get_count(EVENT_STATUS_NEW, false);
}

function events_get_count($status, $is_public = true) {
    global $user;
    if ($is_public) {
        $type = 'public';
    } else {
        $type = 'private';
    }
    $result = db_query('SELECT COUNT(*) AS num FROM events_users AS eu LEFT JOIN content_type_event AS ev ON eu.event_id = ev.nid WHERE ev.field_event_type_value = "%s" AND eu.status = %d AND eu.user_id = %d', $type, $status, $user->uid);
    $count = db_result($result);
    
    return $count;
}

function events_get_events($status, $is_public = true) {
    global $user;
    if ($is_public) {
        $type = 'public';
    } else {
        $type = 'private';
    }
    $result = db_query('SELECT eu.* FROM events_users AS eu LEFT JOIN content_type_event AS ev ON eu.event_id = ev.nid WHERE ev.field_event_type_value = "%s" AND eu.status = %d AND eu.user_id = %d', $type, $status, $user->uid);
    
    $ids = array();
    while($event = db_fetch_array($result)) {
        $ids[] = $event;    
    }
    
    return $ids;
}
function events_views_pre_render(&$view) {
  if($view->name == 'homepage_public_events' && $view->current_display == 'block_2'){
    $items_to_display = 9;
    if($view->result > $items_to_display){
      $new_result = array();
      $result_keys = array_keys($view->result);
      $random_keys = array_rand($result_keys, $items_to_display);
      asort($random_keys);
      for($i=0; $i < $items_to_display && $i < count($random_keys); $i++){
        $new_result[$i] = clone($view->result[$random_keys[$i]]);
      }
      //usort($new_result,'events_sort_event_ads');
      $view->result = $new_result;
    } 
  }
}

function events_sort_event_ads($a, $b)
{
    if (!isset($a->node_data_field_date_field_date_value) || !isset($b->node_data_field_date_field_date_value) ||  $a->node_data_field_date_field_date_value == $b->node_data_field_date_field_date_value) {
        return 0;
    }
    return ($a->node_data_field_date_field_date_value < $b->node_data_field_date_field_date_value) ? -1 : 1;
}


function events_public_page() {
    $html = '';
    $events = array();
    
    $ids = events_get_events(EVENT_STATUS_ACCEPTED, true);
    if (!empty($ids)) {
        foreach ($ids as $event) {
            $node = node_load($event['event_id']);
            $node->event_data = $event;
            $node->friends_going = events_get_friends_going($event['event_id'], $event['user_id']);
            $events[] = node_view($node, true);
        }
    }
    
    $html .= theme('events_invited_list', $events, true);
    
    $events = array();
    $ids = events_get_events(EVENT_STATUS_ACCEPTED, true);
    if (!empty($ids)) {
        foreach ($ids as $event) {
            $node = node_load($event['event_id']);
            $node->event_data = $event;
            $node->friends_going = events_get_friends_going($event['event_id'], $event['user_id']);
            $events[] = node_view($node, true);
        }
    }
    
    $html .= theme('events_accepted_list', $events, true);
    
    $html .= theme('klicango_invite_friends', "$('#active_event').val()");
    
    return $html;
}

function events_private_page() {
    $html = '';
    $events = array();
    
    $ids = events_get_events(EVENT_STATUS_NEW, false);
    if (!empty($ids)) {
        foreach ($ids as $event) {
            $node = node_load($event['event_id']);
            $node->event_data = $event;
            $node->friends_going = events_get_friends_going($event['event_id'], $event['user_id']);
            $events[] = node_view($node, true);
        }
    }
    
    $html .= theme('events_invited_list', $events, false);
    
    $events = array();
    $ids = events_get_events(EVENT_STATUS_ACCEPTED, false);
    if (!empty($ids)) {
        foreach ($ids as $event) {
            $node = node_load($event['event_id']);
            $node->event_data = $event;
            $node->friends_going = events_get_friends_going($event['event_id'], $event['user_id']);
            $events[] = node_view($node, true);
        }
    }
    
    $html .= theme('events_accepted_list', $events, false);
    
    $html .= theme('klicango_invite_friends', "$('#active_event').val()");
    
    return $html;
}

function events_get_friends_going($event_id, $user_id) {
    $result = db_query('SELECT COUNT(*) FROM events_users 
                        WHERE event_id = %d AND user_id IN (
                            SELECT uid AS id FROM friends 
                            WHERE fid = %d UNION SELECT fid AS id FROM friends WHERE uid = %d
                        )', $event_id, $user_id, $user_id);
    $count = db_result($result);
    
    return $count;
}

function events_get_user_activity_stream(){
  global $user;
  $view = views_get_view('nodecomments');
  $view->set_display('block_1');
  $view->set_use_pager(true);
  $view->set_use_ajax(false);
  $view->set_items_per_page(8);
  if(arg(0) == 'user' && arg(1) > 0){
    $user_id = arg(1);  
  }
  else{
    $user_id = $user->uid; 
  }

  $events = array_merge(events_get_events_created_by_user($user_id), events_get_user_events_with_status($user_id));

  $args = array();
  if(!empty($events))
    $args = array(implode('+',$events));
  $view->set_arguments($args);
  
 /* $view->pre_execute($args);
  // Preview the view.
  $output = $view->display_handler->preview();

  $view->post_execute();
  return $output;
   */
  
  return $view->render('block_1');
}


function events_get_latest_events_photos(){
  global $user;
  $events_to_show = 4;
  $photos_to_show = 4;
  
  if(arg(0) == 'user' && arg(1) > 0){   
    $user_id = arg(1);  
    $_user = user_load($user_id);
  }
  else{
    $user_id = $user->uid; 
    $_user = $user;
  }
    
  $photos_res = db_query('select ph.field_comment_photo_fid, nc.nid, f.*,n.title as node_title, evt.field_date_value as event_date,evt_image_file.filepath as event_image
                          FROM `content_field_comment_photo` ph 
                          INNER JOIN node_comments nc on nc.cid = ph.nid
                          INNER JOIN node n on n.nid = nc.nid 
                          INNER JOIN files f on f.fid = ph.field_comment_photo_fid 
                          INNER JOIN content_type_event evt on evt.nid = n.nid 
                          LEFT JOIN content_field_content_images evt_image on evt_image.nid = n.nid 
                          LEFT JOIN files evt_image_file on evt_image_file.fid = evt_image.field_content_images_fid 
                          WHERE nc.nid in (SELECT nid from node where uid = %d AND type = \'event\' and status = 1) 
                          AND field_comment_photo_fid IS NOT NULL
                          GROUP BY nc.nid, ph.field_comment_photo_fid
                          ORDER BY evt.field_date_value DESC
                          ', $user_id);
  
  //$events = events_get_events_created_by_user($user_id);
  //if(count($events) > 0){
   // $photos_res = db_query('select * from `content_field_comment_photo` WHERE nid in (57) and field_comment_photo_fid IS NOT NULL',implode(', ',$events));
    while ($r = db_fetch_array($photos_res)) {
      $photos[$r['nid']]['photos'][$r['field_comment_photo_fid']] = $r;
      $photos[$r['nid']]['node_title'] = $r['node_title'];
      $photos[$r['nid']]['event_date'] = $r['event_date'];
      $photos[$r['nid']]['event_image'] = $r['event_image'];
    }
    $photos = array_slice($photos,0,$events_to_show, true);

    return theme('latest_events_photos', $photos, $photos_to_show);
}

function show_events($date){
  global $user;
  if(arg(0) == 'user' && arg(1) > 0){
    $user_id = arg(1);  
  }
  else{
    $user_id = $user->uid; 
  }

  $event_nids = get_user_events_for_date($user_id, $date);
  $events = array();
  foreach($event_nids as $_nid)
    $events[] = node_view(node_load($_nid), true);
    
  echo theme('events_invited_list', $events, true);
  exit;
}

function get_user_events_for_date($user_id = null, $date = null, $load_full_node = false){
  $events = array();
  if(!empty($date)){
    //First get events that are created by user for this date
    if(empty($user_id)){
      global $user;
      $user_id = $user->uid;
    }  
    
    $res = db_query("SELECT e.nid from {content_type_event} e
                      INNER JOIN {node} n on n.nid = e.nid
                      where uid = %d AND n.status = 1 AND DATE_FORMAT(field_date_value,'%%Y-%%m-%%d') = '%s'",$user_id, $date);
    while ($r = db_fetch_array($res)) {
      if($load_full_node)
        $events[$r['nid']] = node_load($r['nid']);
      else
        $events[] = $r['nid'];
    } 
     
    // Also, select events that are user subscribed to
    $res = db_query("SELECT event_id from {events_users} eu
                      INNER JOIN {content_type_event} e on eu.event_id = e.nid
                      where user_id = %d AND DATE_FORMAT(field_date_value,'%%Y-%%m-%%d') = '%s'",$user_id, $date);
    while ($r = db_fetch_array($res)) {
      if($load_full_node)
        $events[$r['event_id']] = node_load($r['event_id']);
      else
        $events[] = $r['event_id'];
    }
    
  }
  return $events;
}